kind: PersistentVolume
apiVersion: v1
metadata:
  name: k8s-pv-volume
  labels:
    type: local
spec:
  storageClassName: k8s-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/k8s-demo
